-- carga politicas para los hoteles 1 al 12
INSERT INTO politicas (producto_id, politicas_types_id, descripcion) VALUES
(1, 1, 'No fumar'),
(2, 1, 'No fumar'),
(3, 1, 'No fumar'),
(4, 1, 'No fumar'),
(5, 1, 'No fumar'),
(6, 1, 'No se permiten fiestas'),
(7, 1, 'No se permiten fiestas'),
(8, 1, 'No se permiten fiestas'),
(9, 1, 'No se permiten fiestas'),
(10, 1, 'No se permiten fiestas'),
(11, 1, 'Check-out: 10hs'),
(12, 1, 'Check-out: 10hs'),
(3, 1, 'Check-out: 10hs'),
(4, 1, 'Check-out: 10hs'),
(5, 1, 'Check-out: 10hs'),
(6, 1, 'Check-out: 11hs'),
(7, 1, 'Check-out: 11hs'),
(8, 1, 'Check-out: 9hs'),
(9, 1, 'Check-out: 11hs'),
(10, 1, 'Check-out: 10hs'),
(11, 1, 'Check-out: 12hs'),
(12, 1, 'Check-out: 12hs'),
(1, 2, 'Detector de humo'),
(2, 2, 'Detector de humo'),
(5, 2, 'Detector de humo'),
(6, 2, 'Detector de humo'),
(7, 2, 'Detector de humo'),
(8, 2, 'Detector de humo'),
(9, 2, 'Depósito de seguridad'),
(10, 2, 'Depósito de seguridad'),
(11, 2, 'Depósito de seguridad'),
(12, 2, 'Depósito de seguridad'),
(1, 2, 'Depósito de seguridad'),
(2, 2, 'Depósito de seguridad'),
(3, 2, 'Depósito de seguridad'),
(4, 2, 'Depósito de seguridad'),
(5, 2, 'Depósito de seguridad'),
(6, 2, 'Depósito de seguridad'),
(7, 3, 'Cancelación sin costo con 72 hs de anticipación'),
(8, 3, 'Cancelación sin costo con 72 hs de anticipación'),
(9, 3, 'Cancelación sin costo con 72 hs de anticipación'),
(10, 3, 'Cancelación sin costo con 48 hs de anticipación'),
(11, 3, 'Cancelación sin costo con 48 hs de anticipación'),
(12, 3, 'Cancelación sin costo con 48 hs de anticipación'),
(1, 3, 'Cancelación sin costo con 48 hs de anticipación'),
(2, 3, 'No se aceptan cancelaciones'),
(3, 3, 'No se aceptan cancelaciones'),
(4, 3, 'No se aceptan cancelaciones'),
(5, 3, 'No se aceptan cancelaciones'),
(6, 3, 'No se aceptan cancelaciones');