CREATE DATABASE  IF NOT EXISTS `0223TDPRON1C7LAED0621PT_GRUPO5`;
USE `0223TDPRON1C7LAED0621PT_GRUPO5`;

DROP TABLE IF EXISTS `resenias`;
CREATE TABLE `resenias` (
  `resenia_id` int NOT NULL AUTO_INCREMENT,
  `puntaje` float DEFAULT NULL,
  PRIMARY KEY (`resenia_id`)
);
ALTER TABLE resenias AUTO_INCREMENT = 1;