INSERT INTO ciudades (nombre, pais_id) VALUES 
  ('Buenos Aires', 1),
  ('Nueva York', 9),
  ('Tokio', 10),
  ('París', 7),
  ('Madrid', 11),
  ('La Paz', 15),
  ('Lima', 5),
  ('Camboriú', 2),
  ('Medellin', 3),
  ('Bogotá', 3),
  ('Los Ángeles', 9),
  ('San Francisco', 9),
  ('Las Vegas', 9),
  ('Bariloche', 1),
  ('Mar del Plata', 1),
  ('Purmamarca', 1),
  ('Rosario', 1),
  ('Córdoba', 1),
  ('Punta del Este', 8),
  ('Punta del Diablo', 8),
  ('Colonia', 8),
  ('Montevideo', 8),
  ('José Ignacio', 8),
  ('La Paloma', 8),
  ('La paz', 1),
  ('Mendoza', 1),
  ('Córdoba', 1),
  ('La Falda', 1),
  ('Capilla del Monte', 1),
  ('San Clemente del Tuyú', 1),
  ('Santa Teresita', 1),
  ('Villa Gesell', 1),
  ('Santa Clara del Mar', 1),
  ('San Bernardo', 1),
  ('Zapala', 1);